### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by KITSJamesWalker** [robbertkauffman/hippo-addon-spa-integration#1]
If I run 'node src/server' from the demo folder I get:

Error: Cannot find module '<local-path>/hippo-addon-spa-integration/demo/src/server'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

**Comment by KITSJamesWalker** [comment]
Ah ok you need to run it from the demo/spa-app folder
